"""
core/router.py
--------------
Vector-based persona router.

Builds a singleton FAISS ``IndexFlatIP`` from bot persona embeddings at startup
and routes incoming posts to semantically matching bots via cosine similarity.

Embeddings are generated by ``sentence-transformers/all-MiniLM-L6-v2`` through
the HuggingFace Inference API.  Vectors are L2-normalised before indexing so
inner-product search is equivalent to cosine similarity.
"""

import numpy as np
import requests
import faiss

from core.config import settings
from core.logging_config import get_logger
from core.personas import PERSONAS

log = get_logger(__name__)

_HF_API_URL = (
    "https://router.huggingface.co/hf-inference/models/"
    "sentence-transformers/all-MiniLM-L6-v2/pipeline/feature-extraction"
)

_index: faiss.IndexFlatIP | None = None
_bot_ids: list[str] | None = None


def _hf_headers() -> dict[str, str]:
    """Build HuggingFace API request headers with optional bearer token."""
    headers: dict[str, str] = {"Content-Type": "application/json"}
    if settings.hf_token:
        headers["Authorization"] = f"Bearer {settings.hf_token}"
    return headers


def _embed(text: str) -> np.ndarray:
    """
    Fetch an L2-normalised embedding vector from the HuggingFace Inference API.

    Args:
        text: The input text to embed.

    Returns:
        A 1-D float32 numpy array, unit-normalised.

    Raises:
        RuntimeError: On a 401 Unauthorized response.
        requests.HTTPError: On any other non-2xx response.
    """
    response = requests.post(
        _HF_API_URL,
        headers=_hf_headers(),
        json={"inputs": text, "options": {"wait_for_model": True}},
        timeout=30,
    )

    if response.status_code == 401:
        token_hint = (settings.hf_token[:8] + "…") if settings.hf_token else "not set"
        raise RuntimeError(
            f"HuggingFace API 401 Unauthorized. HF_TOKEN={token_hint}. "
            "Ensure .env contains a valid HF_TOKEN=hf_xxxx value."
        )

    response.raise_for_status()

    arr = np.array(response.json(), dtype=np.float32)
    if arr.ndim == 2:
        arr = arr.mean(axis=0)

    norm = np.linalg.norm(arr)
    return arr / (norm + 1e-10)


def build_index() -> None:
    """
    Build the FAISS persona index from all entries in ``PERSONAS``.

    This function is idempotent — subsequent calls after the index is built
    are no-ops.  Called once during application startup.
    """
    global _index, _bot_ids

    if _index is not None:
        return

    log.info("building_persona_index")
    _bot_ids = list(PERSONAS.keys())
    embeddings: list[np.ndarray] = []

    for bot_id in _bot_ids:
        vec = _embed(PERSONAS[bot_id]["description"])
        embeddings.append(vec)
        log.debug("persona_embedded", bot_id=bot_id)

    matrix = np.vstack(embeddings)
    dimension: int = matrix.shape[1]
    _index = faiss.IndexFlatIP(dimension)
    _index.add(matrix)

    log.info("persona_index_ready", total_personas=_index.ntotal, dim=dimension)


def route_post(
    post_content: str,
    threshold: float | None = None,
) -> list[dict[str, float | str]]:
    """
    Route ``post_content`` to all bots whose cosine similarity exceeds ``threshold``.

    Args:
        post_content: The social-media post text to classify.
        threshold:    Minimum cosine similarity score for a match.
                      Defaults to ``settings.router_similarity_threshold``.

    Returns:
        List of ``{"bot_id": str, "similarity": float}`` dicts,
        sorted by similarity descending.
    """
    if _index is None:
        build_index()

    cutoff = threshold if threshold is not None else settings.router_similarity_threshold
    vec = _embed(post_content).reshape(1, -1)
    similarities, indices = _index.search(vec, len(_bot_ids))

    matched = [
        {"bot_id": _bot_ids[idx], "similarity": round(float(sim), 4)}
        for sim, idx in zip(similarities[0], indices[0])
        if sim >= cutoff
    ]
    matched.sort(key=lambda x: x["similarity"], reverse=True)
    return matched


def get_all_scores(post_content: str) -> list[dict[str, float | str]]:
    """
    Return similarity scores for every bot, regardless of threshold.

    Intended for offline evaluation (``eval/eval_router.py``).

    Args:
        post_content: The post text to score against all personas.

    Returns:
        List of ``{"bot_id": str, "similarity": float}`` dicts.
    """
    if _index is None:
        build_index()

    vec = _embed(post_content).reshape(1, -1)
    similarities, indices = _index.search(vec, len(_bot_ids))

    return [
        {"bot_id": _bot_ids[idx], "similarity": round(float(sim), 4)}
        for sim, idx in zip(similarities[0], indices[0])
    ]
